# Active sampler learning experiments.

# Experiment with random explorer, myopic classifier in kitchen.
---
APPROACHES:
  random-explore:
    NAME: "active_sampler_learning"
    FLAGS:
      explorer: "random_nsrts"
ENVS:
  kitchen:
    NAME: "kitchen"
ARGS:
  - "debug"
FLAGS:
  strips_learner: "oracle"
  sampler_learner: "oracle"
  bilevel_plan_without_sim: "True"
  max_initial_demos: 0
  num_train_tasks: 1000
  num_test_tasks: 100
  max_num_steps_interaction_request: 50
  sampler_mlp_classifier_max_itr: 100000
  mlp_classifier_balance_data: False
  pytorch_train_print_every: 10000
  active_sampler_learning_use_teacher: False  # NOTE
  online_nsrt_learning_requests_per_cycle: 10  # NOTE
  num_online_learning_cycles: 25
START_SEED: 123
NUM_SEEDS: 10

# Experiment comparing myopic classifier, fitted Q iteration, and classifier
# with teacher.
---
APPROACHES:
  myopic_classifier:
    NAME: "active_sampler_learning"
    FLAGS:
      active_sampler_learning_model: "myopic_classifier"
      active_sampler_learning_use_teacher: False
  teacher_classifier:
    NAME: "active_sampler_learning"
    FLAGS:
      active_sampler_learning_model: "myopic_classifier"
      active_sampler_learning_use_teacher: True
  fitted_q:
    NAME: "active_sampler_learning"
    FLAGS:
      active_sampler_learning_model: "fitted_q"
      active_sampler_learning_use_teacher: False
ENVS:
  kitchen:
    NAME: "kitchen"
ARGS:
  - "debug"
FLAGS:
  strips_learner: "oracle"
  sampler_learner: "oracle"
  bilevel_plan_without_sim: "True"
  max_initial_demos: 0
  num_train_tasks: 1000
  num_test_tasks: 100
  max_num_steps_interaction_request: 50
  sampler_mlp_classifier_max_itr: 100000
  mlp_classifier_balance_data: False
  pytorch_train_print_every: 10000
  explorer: "random_nsrts"  # NOTE
  online_nsrt_learning_requests_per_cycle: 10  # NOTE
  num_online_learning_cycles: 25
START_SEED: 123
NUM_SEEDS: 10
