# Active sampler learning experiment on Spot.
---
APPROACHES:
  main:
    NAME: "spot_wrapper[active_sampler_learning]"
    FLAGS:
      explorer: "active_sampler"
      active_sampler_explore_task_strategy: "planning_progress"
ENVS:
  spot_bike_env:
    NAME: "spot_cube_env"
    FLAGS:
      spot_robot_ip: "10.17.30.30"
      perceiver: "spot_perceiver"
      execution_monitor: "expected_atoms"
ARGS:
  - "debug"
FLAGS:
  strips_learner: "oracle"
  sampler_learner: "oracle"
  segmenter: "spot"
  bilevel_plan_without_sim: "True"
  max_initial_demos: 0
  num_train_tasks: 1000  # doesn't really matter
  num_test_tasks: 0  # can add back later if we want
  max_num_steps_interaction_request: 50
  sampler_mlp_classifier_max_itr: 100000
  mlp_classifier_balance_data: False
  pytorch_train_print_every: 10000
  active_sampler_learning_use_teacher: False
  online_nsrt_learning_requests_per_cycle: 1
  num_online_learning_cycles: 25
  sesame_task_planner: "fdopt-costs"
  sesame_grounder: "fd_translator"
START_SEED: 123
NUM_SEEDS: 1
