language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - pytest src/ --pylint -m pylint --pylint-rcfile=.predicators_pylintrc
  - pytest tests/ --pylint --pylint-rcfile=.predicators_pylintrc
